### ISSUE TITLE
Java stack error when search a nonexistent string in settings

### ISSUE THREAD

**Issue by 0x524c** [KcNirvana/MA-XML-9.0-PORTUGUESE#1]
I want to report a bug I encountered in Miui9 7.8.10 during a test purposes. I made a Video because it's the easiest way to explain it, I guess.

https://streamable.com/ir0ed

**Comment by KcNirvana** [comment]
Boas...
Ainda não tenho a Miui9 por isso vai ser dificil de encontrar o erro mas vou analisar.
Obrigado.

**Comment by ingbrzy** [comment]
Its about translation issue within these search lines 
https://github.com/KcNirvana/MA-XML-9.0-PORTUGUESE/blob/master/Portuguese/main/Settings.apk/res/values-pt-rPT/strings.xml#L3012-L3196

so remove them or update your translation..
