### ISSUE TITLE
Erro de XML(?) nos Contactos

### ISSUE THREAD

**Issue by fred-cardoso** [KcNirvana/MA-XML-9.0-PORTUGUESE#11]
Boas KcNirvana e Lippe35, parabéns pelo projecto!

Venho aqui deixar um bug que me apareceu hoje na versão developer 7.11.16.
![translation bug](https://user-images.githubusercontent.com/32043667/32968745-42d35744-cbda-11e7-8548-f9bde51cfe6c.png)

Bom fim-de-semana!

**Comment by KcNirvana** [comment]
Boas...
Esquisito porque a mim aparece me bem.
Qual é o modelo do telefone?

**Comment by fred-cardoso** [comment]
Xiaomi Redmi Note 3 SE, Kate.

Não sei se ajuda mas foi a primeira vez que abri a APP e foi instalação clean do 0.

E encontrei outro: https://ibb.co/fWCWk6

Obrigado pela rápida resposta e bom trabalho
