### ISSUE TITLE
Problemas tradução

### ISSUE THREAD

**Issue by nsf1977** [KcNirvana/MA-XML-9.0-PORTUGUESE#13]
Instalei a versão estável da rom xiaomi.eu (9.0) e nas definições, ao aceder às informações do dispositivo, as especificações não correspondem às reais.
Tenho um redmi note 4X que tem as seguintes características:
Chipset snapdragon 625, ecrã de 5.5 pol, bateria de 4100mAh e câmara traseira de 12mp e frontal de 5mp.
Na rom xiaomi.eu, nas especificações do equipamento aparece o seguinte:
Chipset snapdragon  835, ecrã de 5.15 pol, bateria de 3350mAh e câmara traseira de 12mp e frontal de 12mp.
Seguindo as indicações colocadas no forum xiaomi.eu parece ser problema com a linguagem porque se alterar para inglês as especificações apresentadas estão corretas.
https://xiaomi.eu/community/threads/7-12-7.42563/page-15#post-399469

Seguem as imagens que demonstram o relatado.
Sistema em inglês:
![screenshot_2017-12-11-16-33-33-830_com android settings](https://user-images.githubusercontent.com/34452549/33842437-73424186-de92-11e7-8c58-897a84abf8e1.png)

Sistema em português:
![screenshot_2017-12-11-13-54-21-779_com android settings](https://user-images.githubusercontent.com/34452549/33842459-8126056c-de92-11e7-9df1-59e31a006097.png)

**Comment by KcNirvana** [comment]
Boas...
Faz me 1 teste sff
Mete o telemóvel em PT-BR e verifica se está exatamente igual.
Obrigado

**Comment by nsf1977** [comment]
Boas.
Alterando a linguagem para PT-BR o erro das especificações mantém-se exatamente igual ao PT-PT.
Reparei agora numa outra situação que julgo poderá ser também problema de tradução.
Tenho um alarme definido e ao aproximar-se a hora aparece a informação na barra de notificações e ao expandir na descrição um dos carateres é %. 
Aqui está o Screen Shot:
![screenshot_2017-12-12-09-20-41-577_com android deskclock](https://user-images.githubusercontent.com/34452549/33876708-2554fab8-df1e-11e7-80a3-f45d73174133.png)

**Comment by KcNirvana** [comment]
Boas...
Quanto às especificações o problema está na tradução PT-BR mas como a xiaomi retirou isso é esperar pela próxima Stable que saia.
Quanto ao alarme também foi corrigido como podes ver:
![screenshot_2017-12-12-09-47-04-593_com miui home](https://user-images.githubusercontent.com/12718890/33877916-ce57b27e-df21-11e7-825f-475f6b3ec9cb.png)

Neste caso, apenas tens que esperar que saia a próxima stable ou pôr 1 developer.
Obrigado.
Abraço
