### ISSUE TITLE
Opções USB não traduzidas

### ISSUE THREAD

**Issue by hugocard** [KcNirvana/MA-XML-9.0-PORTUGUESE#14]
Versão 8.1.18 - Quando ligado por USB aparece o texto em ingles:
USB for Charging
Touch for more options.

**Comment by KcNirvana** [comment]
Bom dia,
Pode por um screenshot sff?
Obrigado.

**Comment by hugocard** [comment]
Segue em anexo

Em 23/01/2018 11:46 da manhã, "KcNirvana" <notifications@github.com>
escreveu:

**Comment by KcNirvana** [comment]
Boa noite,
O anexo não aparece.
Já agora qual o equipamento?
Obrigado

**Comment by hugocard** [comment]
Boa noite,
Segue a imagem carregada online:
https://imgur.com/a/1R8uy

redmi note 3 pro - kenzo

2018-01-24 21:54 GMT+00:00 KcNirvana <notifications@github.com>:

**Comment by KcNirvana** [comment]
Bom dia,
Já tentaste desligar o cabo e introduzir novamente para ver se a mensagem ainda está em inglês?
É que isso acontece-me quando mudo de idioma.

**Comment by hugocard** [comment]
Já e nunca mudei o idioma

Em 26/01/2018 8:58 da manhã, "KcNirvana" <notifications@github.com>
escreveu:

**Comment by KcNirvana** [comment]
Boas...
O erro ainda se verifica nas novas versões Beta?
Obrigado
