### ISSUE TITLE
Definições Privacidade

### ISSUE THREAD

**Issue by Juvetech** [KcNirvana/MA-XML-9.0-PORTUGUESE#17]
Ainda contêm alguns itens em Ingles.

Ex: Managed Device Info, INstall Unknown apps, Encryption & Credentials

**Comment by KcNirvana** [comment]
Bom dia,
SS por favor.
Obrigado.

**Comment by NunoRocha89** [comment]
Bom dia, 
confirmo na versão 8.3.8 no Mi6.
![screenshot_2018-03-12-06-53-40-394_com android settings](https://user-images.githubusercontent.com/37287217/37281517-35355182-25e9-11e8-8b26-b4840fa51e1e.png)
![screenshot_2018-03-12-06-53-54-282_com android settings](https://user-images.githubusercontent.com/37287217/37281526-3cd3a79a-25e9-11e8-83f9-e7db9559b4ac.png)

**Comment by KcNirvana** [comment]
@NunoRocha89 
Boas.
Corrigido para a próxima versão.
Podes postar SS também nos outros issues?
Obrigado.
Grande abraço

**Comment by NunoRocha89** [comment]
Boas, 
Sim, vou tentar tirar ss às outras situações e posto no devido post.
Hoje ou amanhã partilho os ss.
