### ISSUE TITLE
Definições Browser

### ISSUE THREAD

**Issue by Juvetech** [KcNirvana/MA-XML-9.0-PORTUGUESE#19]
Data Usage Monitor
Newsfeed

**Comment by KcNirvana** [comment]
Bom dia,
SS por favor.
Obrigado.

**Comment by NunoRocha89** [comment]
Confirmo está situação pelo que partilho ss assim que possível.

**Comment by NunoRocha89** [comment]
Bom dia, 
não consegui enviar mais cedo mas aqui estão os screen shots.
![screenshot_2018-03-12-20-28-48-439_com android browser](https://user-images.githubusercontent.com/37287217/37456704-ebc6f32e-2837-11e8-8c1b-5595562a8923.png)
![screenshot_2018-03-12-20-28-55-258_com android browser](https://user-images.githubusercontent.com/37287217/37456705-ebe7926e-2837-11e8-97d2-dc34b20fa8bd.png)
