### ISSUE TITLE
O sistema bloqueia e depois reinicia o telemovel

### ISSUE THREAD

**Issue by rubensilva1993** [KcNirvana/MA-XML-9.0-PORTUGUESE#2]
Boas, estou a usar a versão estável "MI6_V8.2.28.0.NCACNEC"  e estou a utilizar normalmente o telemóvel, quando ele bloqueia e depois reinicia..  Antes desta versão eu estava a usar a "MI6_7.7.17" e não me aconteceu nunca isto... Antes desta "MI6_7.7.17" eu usava uma versão estável e acontecia o mesmo..

**Comment by KcNirvana** [comment]
Boas...
Fizeste os Wipes depois de passares duma Developer para Stable?
Abraço

**Comment by rubensilva1993** [comment]
boas, desculpa só vi agora o e-mail.
fiz todas as wipes, até formatei a memória interna dele ficou tudo a zero.. é o gajo em duas ROMs estáveis que lhe meti ele desliga e ligava sempre.so<http://sempre.so> com esta ROM é que não acontece isso.. não percebo porque . já o.meu irmão tem o mi5 meti a ROM estável e acontece o mesmo.
[cid:_wpsmail@fpgdab9muiud42in68r8iclc.1502925055571]

esta é a que não.me<http://o.me> acontece isso, é uma developer

Enviado do meu telefone Mi
Em 15/08/2017 10:39 da tarde, KcNirvana <notifications@github.com> escreveu:

Boas...
Fizeste os Wipes depois de passares duma Developer para Stable?
Abraço

**Comment by rubensilva1993** [comment]
boas, desculpa só vi agora o e-mail.
fiz todas as wipes, até formatei a memória interna dele ficou tudo a zero.. e o gajo em duas ROMs estáveis que lhe meti ele desliga e liga sempre so com esta ROM é que não acontece isso.. não percebo porque já o meu irmão tem o mi5 meti a ROM estável e acontece o mesmo.  
ele não se desliga sempre, tou a mexer bloqueia e depois reinicia..
a ROM que tenho agora é a 7.7.17  miui 8.6
e neste ele rola bem .

**Comment by KcNirvana** [comment]
Boas...
Pois mas nesse caso tens mesmo que pedir ajuda no fórum xiaomi.eu...
Aqui são apenas as traduções...
Grande abraço
