### ISSUE TITLE
Caracteres chineses na galeria 8.3.8

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MA-XML-9.0-PORTUGUESE#21]
Bom dia, 
quando abro a galeria no meu MI6 com a ROM 8.3.8, se se fizer um scroll down para aparecer a barra de pesquisa, esta aparece com caracteres chineses.

![screenshot_2018-03-15-10-02-51-571_com miui gallery](https://user-images.githubusercontent.com/37287217/37456840-3fc038c8-2838-11e8-8a30-5783b02e7180.png)

Dentro da barra de pesquisa está tudo em Chinês.

![screenshot_2018-03-15-10-04-34-871_com miui gallery](https://user-images.githubusercontent.com/37287217/37456920-673939a4-2838-11e8-887d-b1236e0b8b42.png)

**Comment by KcNirvana** [comment]
Boas...
Esses caracteres tem a ver com a funcionalidade beta chinesa de pesquisar na galeria.
Tens de ir ao Miui Lab e desactivar isso, porque essa pesquisa é online daí os caracteres chineses.
Abraço
