### ISSUE TITLE
Tradução 

### ISSUE THREAD

**Issue by Caldas37** [KcNirvana/MA-XML-9.0-PORTUGUESE#22]
Bom dia, o meu RN3P está a apresentar na tab de ecrã inicial e recentes o texto todo em inglês, já fiz wipe e continua. V.8.3.22
![screenshot_2018-03-23-12-19-03-545_com miui home](https://user-images.githubusercontent.com/24916500/37828932-0949b5b8-2e95-11e8-85da-5b0761ddd5ee.png)

**Comment by KcNirvana** [comment]
Boas...
Estamos a falar do modelo KATE ou KENZO?
Obrigado.

**Comment by Caldas37** [comment]
@KcNirvana o modelo é o Kenzo.

**Comment by KcNirvana** [comment]
Boas...
As alterações feitas relativas ao XML 8.3.22 não chegaram a tempo da compilação de roms da Xiaomi.eu, daí a falta de tradução.
Na próxima versão já estarão corrigidas.
Obrigado.

Abraço
