### ISSUE TITLE
SMS App - Send

### ISSUE THREAD

**Issue by extream87** [KcNirvana/MA-XML-9.0-PORTUGUESE#3]
Hello, in SMS App when you write a message you click in SEND button this button need to be translated to Portuguese = ENVIAR

Thanks

**Comment by KcNirvana** [comment]
Boas...
Podias por aqui um printscreen?
Obrigado

**Comment by extream87** [comment]
Aqui está
![screenshot_2017-08-23-14-36-21-069_com android mms](https://user-images.githubusercontent.com/31280641/29618632-bb1f32b2-8810-11e7-8389-b31f450ce5a0.png)

**Comment by ingbrzy** [comment]
Its your theme issue.. 

set default theme..
