### ISSUE TITLE
Miui 9 7.8.24 clock weather widget

### ISSUE THREAD

**Issue by ICavalera** [KcNirvana/MA-XML-9.0-PORTUGUESE#4]
C
![screenshot_2017-08-29-22-01-01-775_com miui home](https://user-images.githubusercontent.com/31455222/29843962-995e3002-8d05-11e7-9b68-f36eaba1893f.png)
lock weather widget is in English even I have Portuguese language.

**Comment by KcNirvana** [comment]
Hello,
Nice wallpaper.
Nice nick

Ainda não tenho Miui9...
Podes só por 1 ss do widget q tas a escolher?
Obrigado.

**Comment by ICavalera** [comment]
Widget de relógio com o tempo. O widget 4x2.

**Comment by ICavalera** [comment]
Também tem outros pormenores em inglês ainda... Mas se não tens a ROM... Não valerá a pena falar.

**Comment by ICavalera** [comment]
Close
