### ISSUE TITLE
Falta traduzir 1 entrada

### ISSUE THREAD

**Issue by chicolaranja** [KcNirvana/MA-XML-9.0-PORTUGUESE#5]
Olá KcNirvana

Na ROM 7.8.31 encontrei 1 linha por traduzir:

Definições -> Sons e vibração -> Silencioso -> Não perturbe -> Allow popup windows.

Encontrei 1 bug também mas não sei se depende da tradução ou se é da ROM.

Abro as definições e na pesquisa escrevo wh. Assim que escrevo o h tenho um forced Closed do Definições. Enviei relatório.

Devo comunicar no Xiaomi.eu?

**Comment by KcNirvana** [comment]
Boas...
Podes por aqui um SS?
Obrigado.

**Comment by chicolaranja** [comment]
Ok

Aqui vai.

![screenshot_2017-09-08-15-58-36-020_com android settings](https://user-images.githubusercontent.com/31771481/30217816-33fb7038-94af-11e7-990a-c4857602b872.png)

Sobre o FC o melhor é mesmo

**Comment by KcNirvana** [comment]
Boas.
Tens a certeza que tás no idioma correcto?
É que esse Não perturbe não existe em PT-PT mas sim em PT-BR

**Comment by chicolaranja** [comment]
Sim, tenho idioma PT-PT

Idioma: Português (Portugal)

MIUI 9, ROM 7.8.31.
![screenshot_2017-09-08-16-19-10-058_com android settings](https://user-images.githubusercontent.com/31771481/30218713-ae49c554-94b1-11e7-8dfa-83f5112ea2d7.png)

![screenshot_2017-09-08-16-23-24-661_com android settings](https://user-images.githubusercontent.com/31771481/30218942-6d683a92-94b2-11e7-84de-24d3619758da.png)

**Comment by KcNirvana** [comment]
Peço desculpa por te estar a dar tanto trabalho.
Última pergunta (Aliás devia ter sido a primeira 👍 )
Qual é o telemóvel?

**Comment by chicolaranja** [comment]
Não há problema ;)

O telemóvel é um Redmi 4X aka santoni.

Sobre o FC da pesquisa nas definições o melhor é mesmo abrir no fórum um tópico sobre isso não?

**Comment by KcNirvana** [comment]
Boas...
Não o FC da pesquisa é mesmo da tradução mas está corrigido nesta versão.
O que te posso dizer é para sacares a nova rom 7.9.7 xiaomi.eu e validares se ainda está assim.

**Comment by chicolaranja** [comment]
Desculpa a demora
Amanhã instalo a 7.9.7 e depois dou feedback.

Fim de semana é menos tecnológico para mim ;)

**Comment by chicolaranja** [comment]
Ois.

Qual é a versão 7.9.7 que queres que experimente?
Xiaomi.eu apenas encontro 8.2.18.0 estável e 7.8.31 Beta.

Global/Chinesa Beta é que tem 7.9.7. É esta?

![redmi4x](https://user-images.githubusercontent.com/31771481/30332725-fc8f6344-97d2-11e7-9ac9-58ba1629c973.png)

Obrigado

**Comment by KcNirvana** [comment]
Boas...
Esta tradução é só da Xiaomi.eu.
Tens a nova 7.9.7 da Xiaomi.eu aqui:
https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/MIUI-WEEKLY-RELEASES/7.9.7/xiaomi.eu_multi_HM4X_7.9.7_v9-7.1.zip/download

**Comment by chicolaranja** [comment]
Boa tarde @KcNirvana 

Actualização de estado:

O FC já não acontece 👍 

A entrada que indiquei como não traduzida de Allow Popup Window continua não traduzida 👎 

ROM MIUI9 by xiaomi.eu 7.9.7@Redmi 4X

Se precisares de mais algum teste avisa. O meu maior problema é mesmo ao instalar a ROM ter que configurar os temas e ando sempre à caça para saber onde mexer além do medo de brickar o telemóvel... marretices de maçarico 😃

**Comment by KcNirvana** [comment]
Corrigido.
Muito obrigado pelo erro reportado.
E mais erros que encontrares já sabes.
Abraço

**Comment by chicolaranja** [comment]
De nada.

Se encontrar mais alguma coisa eu aviso 😄
