### ISSUE TITLE
Tradução na app pesquisar.

### ISSUE THREAD

**Issue by Caldas37** [KcNirvana/MA-XML-9.0-PORTUGUESE#6]
@KcNirvana na versão 7.9.21, quando se faz deslizar para cima no ecrã da pesquisa, se fores a versão da apk mostra a info em chinês. RN3P (Kenzo)
![screenshot_2017-09-24-14-00-17-175_com android quicksearchbox](https://user-images.githubusercontent.com/24916500/30782887-c6a5ae74-a131-11e7-8799-577b42282465.png)
![screenshot_2017-09-24-13-59-09-030_com android quicksearchbox](https://user-images.githubusercontent.com/24916500/30782888-c6a61a12-a131-11e7-9979-5183deab8c71.png)

**Comment by ingbrzy** [comment]
not translatable.. online resources..
