### ISSUE TITLE
Missed translation

### ISSUE THREAD

**Issue by GilMateus** [KcNirvana/MA-XML-9.0-PORTUGUESE#7]
Hi, so I detected a missed translation on the contacts info page send you a screenprint
https://photos.app.goo.gl/kUArbBCVMij7A7T22

**Comment by KcNirvana** [comment]
Boas...
Estamos a falar de que versão?
Obrigado.

**Comment by GilMateus** [comment]
Boas
Atualizei hoje mesmo para a versão MIUI 9 7.10.19 e nesta versão o que
reportei já está corrigido. A versão a q me referia era a MIUI 9 7.10.12 e
tinha me deparado ontem com o erro mas após pesquisa nada encontrei e
decidi reportar a situação para alertar.

Obrigado pela atenção


Em 20/10/2017 11:58 da manhã, "KcNirvana" <notifications@github.com>
escreveu:

**Comment by KcNirvana** [comment]
Obrigado eu pelo alerta.
Grande abraço
