### ISSUE TITLE
Chinese characters on accessibility settings menu

### ISSUE THREAD

**Issue by rictec** [KcNirvana/MA-XML-9.0-PORTUGUESE#8]
there are Chinese characters on the setting menu in accessibility options ...

uma das opções do menu na acessibilidade contem caracteres chineses não se sabe o que está escrito em português

**Comment by rictec** [comment]
![screenshot_2017-11-10-04-38-23-078_com android settings](https://user-images.githubusercontent.com/635171/32643253-00a1e3f8-c5d2-11e7-8538-072c295b7205.png)

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Obrigado.
Abraço
